### ISSUE TITLE
White margin is control

### ISSUE THREAD

**Issue by zanjs** [skip2/go-qrcode#10]
White margin is too big!

 I hope to be a little smaller?!

**Comment by yourchanges** [comment]
how to implement it? any ideas?

**Comment by skip2** [comment]
The fixed size image option currently scales the QR Code to fit in the fixed size image, however this sometimes results in large padding, like in these two 98px and 99px images (same data encoded):

https://skip.org/drop/qrcodes/qr98-old.png
https://skip.org/drop/qrcodes/qr99-old.png

We could add an option to generate variable sized images instead. The library would decide how big the output image would be, with some scaling factor, e.g.:

https://skip.org/drop/qrcodes/qr4.png (4px sized QR Code "pixels")
https://skip.org/drop/qrcodes/qr5.png (5px sized QR Code "pixels")

If you're using these on web pages, you can fix the image size with HTML (e.g. like < img src="qrcode.png" width="250" >), and you've got a nicely scaled/fixed size QRCode.

This could be forced intro the existing API by specifying the scaling factor as a negative size, e.g.
err := qrcode.WriteFile("https://example.org", qrcode.Medium, -5, "qr.png")

You'll still have the white padding around the outside (as per the QR Code specification), but it'll be the minimum required.

Would that help?

**Comment by skip2** [comment]
This is easy to do, I'm happy to implement if you like.

**Comment by zanjs** [comment]
@skip2 Thinks 🤞

**Comment by skip2** [comment]
I implemented this here:

"To generate a variable sized image instead, specify a negative size (in place of the 256 above), such as -4 or -5. Larger negative numbers create larger images: A size of -5 sets each module (QR Code "pixel") to be 5px wide/high." ...

https://godoc.org/github.com/skip2/go-qrcode

best,

Tom
