### ISSUE TITLE
Add color parameters to WriteFile

### ISSUE THREAD

**Issue by onodera-punpun** [skip2/go-qrcode#13]
Would this be possible?

**Comment by skip2** [comment]
You can change the QR Code color by setting the ForegroundColor/BackgroundColor (by default these are color.Black and color.White respectively): 

https://godoc.org/github.com/skip2/go-qrcode#QRCode

**Comment by onodera-punpun** [comment]
Ah thanks, for some reason I thought this would take a lot more effort. Example for someone with the same problem as me in the future:

```go
	qr, err := qrcode.New("https://example.org", qrcode.Medium)
	if err != nil {
		log.Fatal(err)
	}

	qr.BackgroundColor = color.black
	qr.ForegroundColor = color.White

	qr.WriteFile(256, "./qrcode.png")
}
```


Though i still think something like the following would be nice to have:

```go
err := qrcode.WriteFileColor("https://example.org", qrcode.Medium, 256, color.White, color.Black "qr.png")
``

**Comment by onodera-punpun** [comment]
Added in https://github.com/skip2/go-qrcode/commit/429dd1126e8c5280943e99793a3783ef8f0d5d29 :)
