### ISSUE TITLE
how to adjust the padding when QR output to file

### ISSUE THREAD

**Issue by jiaohu** [skip2/go-qrcode#17]
----
my code

```
func TestCreateQrCode(t *testing.T) {
	qrcode.WriteFile("http://www.baidu.com", qrcode.Medium, 256, "qr3.png")
}
```
----
then i get the answer like this
![qr3](https://user-images.githubusercontent.com/13608671/47896818-1b61c900-deaa-11e8-9409-465a5c3c59fd.png)
the white spacing is widely

**Comment by Cr4psy** [comment]
The padding is due to the quiet zone around the QRCode.
It would be great to be able to remove it.

**Comment by goribun** [comment]
Picture cropping almost 75% is ok.

**Comment by skip2** [comment]
This has been fixed in https://github.com/skip2/go-qrcode/pull/24 . Borders are now made the minimum size possible. There's also now an option to disable borders entirely too.
