### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by yaphper** [skip2/go-qrcode#21]
Is there a memory leak problem with this library?
There is a web api with my application for generating QRCode.
I found that the memory footprint would be very high after many requests to this api and do not come down.

go version go1.11.2 windows/amd64

My Code like this:

```golang
func UserAuthQRCode(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	w.Header().Set("Content-Type", "image/png")
	authUrl := "..."
	qrCodeImg, err := qrcode.Encode(
		authUrl,
		qrcode.Medium,
		256)
	if err != nil {
		http.Error(w, "Internal Error", http.StatusInternalServerError)
		return
	}
	_, _ = w.Write(qrCodeImg)
	return
}
```

**Comment by sthales** [comment]
Hey @link-duan, did you found any solution?

**Comment by skip2** [comment]
I'll check to see if this is a problem. How many QR codes are you generating at a time?

**Comment by DVSoftware** [comment]
It seems that this issue still exists. I can see memory footprint raising with each qr code generated.
