### ISSUE TITLE
码眼不符合1:1:3:1:1

### ISSUE THREAD

**Issue by yuedf** [skip2/go-qrcode#38]
qrcode.WriteFile("123", qrcode.Highest, 100, "qr_highest.png")

**Comment by skip2** [comment]
Here's what I generated on the latest da1b6568686e89143e94f980a98bc2dbd5537f13 version:
![](https://skip.org/drop/qr_highest.png)

**Comment by yuedf** [comment]
> Here's what I generated on the latest [da1b656](https://github.com/skip2/go-qrcode/commit/da1b6568686e89143e94f980a98bc2dbd5537f13) version:
> ![](https://camo.githubusercontent.com/e87058a4a87c6c7db2791b713d551bece2048129/68747470733a2f2f736b69702e6f72672f64726f702f71725f686967686573742e706e67)

![image](https://user-images.githubusercontent.com/40194189/85190278-5156f980-b2e9-11ea-8ea8-a89c80810df4.png)
左边黑边是4格，右边黑边是3格

**Comment by yuedf** [comment]
> > Here's what I generated on the latest [da1b656](https://github.com/skip2/go-qrcode/commit/da1b6568686e89143e94f980a98bc2dbd5537f13) version:
> > ![](https://camo.githubusercontent.com/e87058a4a87c6c7db2791b713d551bece2048129/68747470733a2f2f736b69702e6f72672f64726f702f71725f686967686573742e706e67)
> 
> ![image](https://user-images.githubusercontent.com/40194189/85190278-5156f980-b2e9-11ea-8ea8-a89c80810df4.png)
> 第一个码眼左边黑边是4格，右边黑边是3格

**Comment by skip2** [comment]
There are two image modes:

1) Fixed image size: (e.g. 100x100px). The QR code is resized to be as large as possible within the 100x100px. This means some columns/rows in the QR code have more or less pixels, like your image.
```qrcode.WriteFile("123", qrcode.Highest, 100, "qr_highest.png")```

![](https://user-images.githubusercontent.com/40194189/85190278-5156f980-b2e9-11ea-8ea8-a89c80810df4.png)

2) Variable image size. In this mode, images have variable size, but the QR code columns/rows are all the same width/height:
```qrcode.WriteFile("123", qrcode.Highest, -3, "qr.png")```

![](https://skip.org/drop/qr_fixed_spacing.png)

You can use HTML/CSS to resize these generated images on a web page for example.

thank you! :)

skip2

**Comment by yuedf** [comment]
thanks
