### ISSUE TITLE
optimizing padding when write to output file

### ISSUE THREAD

**Issue by emildd** [skip2/go-qrcode#4]
Hi. can I change the padding option before output will be generate to file image?

**Comment by skip2** [comment]
The QR code spec specifies the minimum amount of padding. Invariably QR code readers can handle less padding though.

At the moment QR codes are written to fixed sized images (e.g. the 256 pixel example), which results in a varying amount of padding and a varying size QR code, depending on the amount of information encoded. 

The varying padding is kind of undesirable, do you mean an option to give  "the minimum size QR code possible, using blocks X pixels wide?". i.e. no extra unnecessary padding, or something else?

thanks,

Tom

**Comment by emildd** [comment]
thank you for feedback tom.
yes I have. for the case at the output size width and height is 120px, but size square of qrcode is 100px, there is some padding at the output file.
how to remove the padding ? actually the output file is haven't the padding.

Thank you

**Comment by skip2** [comment]
This has been fixed in https://github.com/skip2/go-qrcode/pull/24 . Borders are now made the minimum size possible. There's also now an option to disable borders entirely too.
