### ISSUE TITLE
Can I just get the matrix? I want to print it to the console / 可以直接拿到矩阵吗，我想打印到控制台

### ISSUE THREAD

**Issue by kirito41dd** [skip2/go-qrcode#46]
Can I just get the matrix? I want to print it to the console / 可以直接拿到矩阵吗，我想打印到控制台
thanks / 谢谢

**Comment by benjamin-rood** [comment]
Yes, use the `Bitmap` method on the encoded PNG byte array.

https://pkg.go.dev/github.com/skip2/go-qrcode#QRCode.Bitmap
