### ISSUE TITLE
能否支持二维码下方添加文本

### ISSUE THREAD

**Issue by lmb1113** [skip2/go-qrcode#56]
能否支持二维码下方添加文本，我在代码中没看到相关内容

**Comment by iuroc** [comment]
下方添加文本，你直接打印字符串不就可以了

**Comment by lmb1113** [comment]
> 下方添加文本，你直接打印字符串不就可以了

感谢答复，几年前才疏学浅，对go不够精通，后来者如有相关需求，建议使用draw.Draw重绘即可

**Comment by iuroc** [comment]
@lmb1113 大佬能不能看看这个问题：https://github.com/iuroc/bilidown/issues/3
