### ISSUE TITLE
Go-LoggedAccountStats package missing request.

### ISSUE THREAD

**Issue by WhipMeHarder** [skip2/go-qrcode#62]
When calling the QRcode library, "go-qrcode", Go keeps referencing a "go-LoggedAccountStats", and asking for it to be installed. Is it possible to remove all references to "LoggedAccountStats" from go.qrcode?

WhipMeHarder

**Comment by skip2** [comment]
Hello,

There are no references to that string in go-qrcode, nor does it import any other external modules.

How did you obtain go-qrcode?
Could you paste the error message you are seeing?

thanks,

skip2

**Comment by WhipMeHarder** [comment]
Hi Skip2,
That is exactly the problem! I could not find any references to it when I trawled through your code! And, when I installed and reinstalled your package, I kept getting the same error.

Ok. This is how it all started - if my memory serves me correctly. - I found a file on my pc called "qrcode", and it had the following imports: - 

        ´"github.com/skip2/go-qrcode"
	//"github.com/skip2/go-LoggedAccountStats"
	//"github.com/mattn/go-colorable"
	"image/png"
	nbytes "bytes"´

I was experimenting with other snippets of code, but they were removed. There was some other code that was obsoleted out: It was the following: -

`/*
type LoggedAccountStatsRecoveryLevel LoggedAccountStats.RecoveryLevel
type LoggedAccountStatsRecoveryLevels struct {
	Low     LoggedAccountStatsRecoveryLevel
	Medium  LoggedAccountStatsRecoveryLevel
	High    LoggedAccountStatsRecoveryLevel
	Highest LoggedAccountStatsRecoveryLevel
}*/`

There are a lot of other supporting functions for " LoggedAccountStatsRecoveryLevels", in the file, which have also been obsoleted out - and then finally removed.

Anyway, when I ran the code through Visual Studio, via the Terminal, I kept getting the warning that " LoggedAccountStatsRecoveryLevels" was "undefined".

As I said earlier, all references were obsoleted out, but the terminal kept asking for it. I checked all file references on your Github account - to no avail. However, all reinstalls have failed. This is the error I keep receiving when I try to run your package: -

`.\qrtst.go:14:16: undefined: RecoveryLevel
.\qrtst.go:18:18: undefined: color        
.\qrtst.go:19:18: undefined: color        
.\qrtst.go:24:11: undefined: dataEncoder  
.\qrtst.go:25:10: undefined: qrCodeVersion
.\qrtst.go:27:10: undefined: bitset       
.\qrtst.go:28:10: undefined: symbol`

When I silence those errors, I keep getting more and more "undefined" errors for every variable and function called.
So, at the moment, I am trying to rebuild all files from your package at this address here -

 "https://github.com/skip2/go-qrcode/blob/da1b6568686e/qrcode.go" 

Manually, as it seems as though not all files are present on my pc.

Unfortunately, I have spent too long trying to resolve this issue, as so much of the data from the many terminals I had opened have been lost, when they were closed; as I was looking for alternative answers.

WhipMeHarder

**Comment by WhipMeHarder** [comment]
The issue has finally been resolved! I still do not know why I was getting "RecoveryLevel" alerts, even when all the commented out code was removed! I had to remove all old "skip2" files and folders, then rebuild the directory manually.
